### ISSUE TITLE
Help for installation

### ISSUE THREAD

**Issue by abdmun8** [rofyfirm/EFI-Clover-A456URK#1]
Hi, I want to try to install hackintosh on my device, its same as yours, I choose mojave. I download mac OS using gibmacOS software from github, to get full macOS installer. Could you please help me with step by step installation?
I copy the EFI folder to my EFI partition as you mention but its not working, it stuck at > kextd stall AppleACPICPU. then it said service exited with abnormal code 1

**Comment by abdmun8** [comment]
Hi, finally I can install mac os using your another repository that using opencore bootloader, but my wlan card is not working yet, thank you for your EFI

**Comment by rofyfirm** [comment]
Hi, you should check the config.plist with propertree. If the
IO80211Family.kext related config are disabled, please enable it first

**Comment by abdmun8** [comment]
Hi, thank you for your advice, maybe I will test on another installation. In my case, I have to disable SIP on recovery because when I check on hackintool this kext is not installed, when I try to reinstall it, it said integrity invalid or something like that. After disabling SIP its work fine. Thanks for your EFI again.
